version: '3'

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: bot/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/data/event_bot
    depends_on:
      - php-fpm
    labels:
      - traefik.backend=web
      - traefik.frontend.rule=Host:${APP_URL};PathPrefix:/
      - traefik.frontend.priority=1
      - traefik.port=80
    networks:
      - app-network

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    image: bot/php-fpm
    container_name: php
    volumes:
      - ./code:/data/event_bot
    depends_on:
      - db
    labels:
      - traefik.enable=false
    networks:
      - app-network

  db:
    restart: always
    image: postgres:11.6-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    labels:
      - traefik.enable=false
    networks:
      - app-network

  traefik:
    image: traefik:1.7-alpine
    depends_on:
      - php-fpm
      - nginx
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    command: --docker
    labels:
      - traefik.enable=false

volumes:
  postgres_volume:

networks:
  app-network:
    driver: bridge